/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Adriana Barboza
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form ProductMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ViewProducts = new javax.swing.JButton();
        jButton_ViewShoppingCart = new javax.swing.JButton();
        jButton_DeleteUser = new javax.swing.JButton();
        jButton_AdminProducts = new javax.swing.JButton();
        jButton_AdminUsers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_ViewProducts.setBackground(new java.awt.Color(0, 153, 153));
        jButton_ViewProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ViewProducts.setText("ViewProducts");
        jButton_ViewProducts.setToolTipText("");
        jButton_ViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewProductsActionPerformed(evt);
            }
        });

        jButton_ViewShoppingCart.setBackground(new java.awt.Color(0, 153, 153));
        jButton_ViewShoppingCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ViewShoppingCart.setText("ViewShoppingCart");
        jButton_ViewShoppingCart.setToolTipText("");

        jButton_DeleteUser.setBackground(new java.awt.Color(255, 0, 51));
        jButton_DeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_DeleteUser.setText("Close");
        jButton_DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteUserActionPerformed(evt);
            }
        });

        jButton_AdminProducts.setBackground(new java.awt.Color(0, 153, 153));
        jButton_AdminProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_AdminProducts.setText("AdminProducts");
        jButton_AdminProducts.setToolTipText("");
        jButton_AdminProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdminProductsActionPerformed(evt);
            }
        });

        jButton_AdminUsers.setBackground(new java.awt.Color(0, 153, 153));
        jButton_AdminUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_AdminUsers.setText("AdminUsers");
        jButton_AdminUsers.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_AdminProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton_AdminUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_ViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton_ViewShoppingCart)))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AdminUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AdminProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ViewShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton_DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleteUserActionPerformed

    private void jButton_ViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ViewProductsActionPerformed

    private void jButton_AdminProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdminProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AdminProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AdminProducts;
    private javax.swing.JButton jButton_AdminUsers;
    private javax.swing.JButton jButton_DeleteUser;
    private javax.swing.JButton jButton_ViewProducts;
    private javax.swing.JButton jButton_ViewShoppingCart;
    // End of variables declaration//GEN-END:variables
}
