/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Adriana Barboza
 */
public class ProductMenu extends javax.swing.JFrame {

    /**
     * Creates new form ProductMenu
     */
    public ProductMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ProductName = new javax.swing.JLabel();
        jLabel_ProductPrice = new javax.swing.JLabel();
        jLabel_ProductType = new javax.swing.JLabel();
        jLabel_ProductTrade = new javax.swing.JLabel();
        jLabel_ProductCategory = new javax.swing.JLabel();
        jTextField_ProductName = new javax.swing.JTextField();
        jTextField_ProductTrade = new javax.swing.JTextField();
        jFormattedTextField_ProductPrice = new javax.swing.JFormattedTextField();
        jSpinner_ProductType = new javax.swing.JSpinner();
        jComboBox_ProductCategory = new javax.swing.JComboBox<>();
        jButton_CreateProduct = new javax.swing.JButton();
        jButton_ViewListofProducts = new javax.swing.JButton();
        jButton_UpdateProduct = new javax.swing.JButton();
        jButton_ViewProduct = new javax.swing.JButton();
        jButton_DeleteProduct = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel_ProductName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_ProductName.setText("Product Name");

        jLabel_ProductPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_ProductPrice.setText("Product Price");

        jLabel_ProductType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_ProductType.setText("Product Type");

        jLabel_ProductTrade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_ProductTrade.setText("Product Trade");

        jLabel_ProductCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_ProductCategory.setText("Product Category");

        jFormattedTextField_ProductPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jSpinner_ProductType.setModel(new javax.swing.SpinnerListModel(new String[] {"Hamburguer", "Cheeseburguer", "Hot dog", "Nuggets", "Fried chicken", "French fries ", "Taco", "Burrito", "Pizza", "Cheese sticks", "Chips", "Bacon", "Croissant", "Coffee", "Lemonade", "Iced tea", "Milshake", "Water", "Beer", "Wine", "Sundae", "Brownie", "Ice Cream", "Donut", "Soda", "Coke"}));

        jComboBox_ProductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entries", "Main plate", "Accompaniment", "Beverage", "Dessert" }));

        jButton_CreateProduct.setBackground(new java.awt.Color(0, 153, 153));
        jButton_CreateProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_CreateProduct.setText("Create Product");
        jButton_CreateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateProductActionPerformed(evt);
            }
        });

        jButton_ViewListofProducts.setBackground(new java.awt.Color(0, 153, 153));
        jButton_ViewListofProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ViewListofProducts.setText("View List of Products");
        jButton_ViewListofProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewListofProductsActionPerformed(evt);
            }
        });

        jButton_UpdateProduct.setBackground(new java.awt.Color(0, 153, 153));
        jButton_UpdateProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_UpdateProduct.setText("Update Product");

        jButton_ViewProduct.setBackground(new java.awt.Color(0, 153, 153));
        jButton_ViewProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ViewProduct.setText("View Product");

        jButton_DeleteProduct.setBackground(new java.awt.Color(0, 153, 153));
        jButton_DeleteProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_DeleteProduct.setText("Delete Product");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Clear List of Products");

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_ProductPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ProductType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ProductTrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ProductCategory, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_ProductName)
                            .addComponent(jTextField_ProductTrade)
                            .addComponent(jFormattedTextField_ProductPrice)
                            .addComponent(jSpinner_ProductType)
                            .addComponent(jComboBox_ProductCategory, 0, 188, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CreateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_UpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_DeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_ViewListofProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_ViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_ProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_ProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ProductTrade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ProductTrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_ProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CreateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ViewListofProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_UpdateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton_ViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_DeleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CreateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CreateProductActionPerformed

    private void jButton_ViewListofProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewListofProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ViewListofProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_CreateProduct;
    private javax.swing.JButton jButton_DeleteProduct;
    private javax.swing.JButton jButton_UpdateProduct;
    private javax.swing.JButton jButton_ViewListofProducts;
    private javax.swing.JButton jButton_ViewProduct;
    private javax.swing.JComboBox<String> jComboBox_ProductCategory;
    private javax.swing.JFormattedTextField jFormattedTextField_ProductPrice;
    private javax.swing.JLabel jLabel_ProductCategory;
    private javax.swing.JLabel jLabel_ProductName;
    private javax.swing.JLabel jLabel_ProductPrice;
    private javax.swing.JLabel jLabel_ProductTrade;
    private javax.swing.JLabel jLabel_ProductType;
    private javax.swing.JSpinner jSpinner_ProductType;
    private javax.swing.JTextField jTextField_ProductName;
    private javax.swing.JTextField jTextField_ProductTrade;
    // End of variables declaration//GEN-END:variables
}
